"""empty message

Revision ID: 17f9ed4c48f7
Revises: a4bcbb77dae2
Create Date: 2023-08-23 15:45:12.010282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f9ed4c48f7'
down_revision = 'a4bcbb77dae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.drop_column('time_created')

    # ### end Alembic commands ###
