"""empty message

Revision ID: a4bcbb77dae2
Revises: b94fef5ecb38
Create Date: 2023-08-22 14:42:35.506101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4bcbb77dae2'
down_revision = 'b94fef5ecb38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hmo', sa.String(length=10), nullable=False))
        batch_op.drop_column('hmo_provider')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hmo_provider', sa.VARCHAR(length=10), nullable=False))
        batch_op.drop_column('hmo')

    # ### end Alembic commands ###
